deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - scp docker-compose.swarm.yml deploy.sh adam@$VPS_HOST:/home/adam/e-commerce/
    - ssh adam@$VPS_HOST "cd /home/adam/e-commerce && chmod +x deploy.sh && ./deploy.sh"
  only:
    - main
