name: Sync to GitLab

on:
  push:
    branches:
      - main 

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/adamgarchi/e-commerce-docker.git
          git push --mirror gitlab
