name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to avoid "shallow update not allowed"

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/adamgarchi/e-commerce-docker.git
          git push --force --all gitlab  # Push all branches
          git push --force --tags gitlab  # Push all tags
